# Generated by Django 2.2.28 on 2025-11-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.JobCategory'),
        ),
    ]
